[theme]
base = "light"                       # app uses light theme
primaryColor = "#4A79BD"             # buttons, sliders, highlights
backgroundColor = "#FFFFFF"          # page background
secondaryBackgroundColor = "#F5F7FC" # cards/sidebar (soft tint)
textColor = "#231F20"                # main text color
font = "sans serif"                  # or "serif" | "monospace"
